export function Report() {
  // The golden diff report is generated by Python during CI
  // and placed at /tikzjs/report/index.html
  const base = import.meta.env.BASE_URL
  return (
    <iframe
      src={`${base}report/index.html`}
      style={{
        width: '100%',
        height: '100%',
        border: 'none',
      }}
      title="Golden Diff Report"
    />
  )
}
