/**
 * Golden tests: compare tikzjs SVG output against reference SVGs.
 *
 * Reference SVGs are generated by TexLive (pdflatex + dvisvgm) and
 * committed to test/golden/refs/. If a ref doesn't exist, the test
 * checks structural validity only.
 *
 * Run reference generation with: bash scripts/generateGolden.sh
 *
 * Comparison modes:
 * 1. Structural: check that SVG elements are present and non-empty
 * 2. Element count: check that paths/nodes roughly match (within tolerance)
 *
 * For pixel-accurate comparison, set GOLDEN_PIXEL_DIFF=1 env var.
 * This requires 'sharp' and 'pixelmatch' to be installed.
 */

import * as fs from 'fs'
import * as path from 'path'
import { generate } from '../../src/index'

const FIXTURES_DIR = path.join(__dirname, 'fixtures')
const REFS_DIR = path.join(__dirname, 'refs')

// Get all fixture files
const fixtures = fs.readdirSync(FIXTURES_DIR)
  .filter(f => f.endsWith('.tikz'))
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))

describe('Golden tests', () => {
  for (const fixture of fixtures) {
    const name = fixture.replace('.tikz', '')
    const tikzPath = path.join(FIXTURES_DIR, fixture)

    test(`golden: ${name}`, () => {
      const tikzSource = fs.readFileSync(tikzPath, 'utf8')

      // Generate SVG
      let svgOutput: string
      try {
        svgOutput = generate(tikzSource)
      } catch (err: any) {
        // Parser/generator errors are test failures
        throw new Error(`Failed to render ${name}: ${err.message}`)
      }

      // Basic structural checks
      expect(svgOutput).toBeTruthy()
      expect(svgOutput).toContain('<svg')
      expect(svgOutput).toContain('</svg>')
      expect(svgOutput.length).toBeGreaterThan(50)

      // Check ref exists
      const refPath = path.join(REFS_DIR, `${name}.svg`)
      if (!fs.existsSync(refPath)) {
        // No ref yet — just validate structure
        console.log(`  [no ref] ${name}: structural check passed (${svgOutput.length} bytes)`)
        return
      }

      // Structural comparison against ref
      const refSvg = fs.readFileSync(refPath, 'utf8')
      const ourPathCount = countElements(svgOutput, '<path')
      const refPathCount = countElements(refSvg, '<path')
      const ourNodeCount = countElements(svgOutput, '<g')
      const refNodeCount = countElements(refSvg, '<g')

      // Allow up to 50% difference in element counts (SVG structures differ between renderers)
      if (refPathCount > 0) {
        const ratio = ourPathCount / refPathCount
        expect(ratio).toBeGreaterThan(0.1)
      }

      console.log(`  ${name}: paths=${ourPathCount}/${refPathCount}, groups=${ourNodeCount}/${refNodeCount}`)
    })
  }
})

function countElements(svg: string, tag: string): number {
  return (svg.match(new RegExp(tag, 'g')) ?? []).length
}
